replicaCount: 1

image:
  repository: 805400277714.dkr.ecr.us-east-2.amazonaws.com/backend
  tag: "1.0.0"    # 기본값, CI/CD에서 ai_value.yaml로 override
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}
