---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-secrets
  namespace: dev-system
spec:
  encryptedData:
    B_DOMAIN: AgATM2wcQeg2mJw0/raa5bcb8tF02AwCNIuDdZqwK+WHKoF8NBd63bZmDTrGQR2Vdwj8oQpcJZTUhj/y9EQ6VvYpBvPyHrpPg46wCf8csgvEHbjWmPV9iohBDbHj2cOEr3soDbttN6bvZ3YVnX9pKICeKddrl9cvbzIPHmHI+DkDEsHqA+L22gQ+PpHPRyTzoakmmm8NYNQM6y0kbR3E0ZriMKJWoIiE4XLizGUzEc74qAc1+Mg6zOPBM7r9hk7yW/IDVxU/gbwTRFl0LZfLDpQI9t3PPyZQFSGIigHQ6bjLXmCIV0f0SsoiQxPmCu8PquuH/V17xbg1zzctTDlJwWzqgmpl1R+qS4CAuyWZzXZzgNiCwjvfttpoM8jezvDehhdVhiLyldVn5vgNM7v2AMqYJEMI2EHKd4+kRWc79FsMkkTnmXst5JSiGIVKcR9vO6/N2QLRAPjwnpo0XHvtjRUlhzgxOHQfwrGI9CN+vJ+PNTNfbjY2YWT3APGhAUHLmoHm5bVwMbDiFo1x8q1rm2SagXMXKyqmfjIUwdNrYbn6FilcfAO9sd1k3uQyJsSJxN1uGZDKWHh8doyph59QH2qoFi/7x9OEeljRcXCob7VrM/UYEa7pwVat1huO4cHbpnZtIahC/1Z5Nupc0onwsOspycqbO9PwchtPCQOAvCTveO668PR9UgSVOk5lFOyg/qX55YAP6dbsTKjqklFO1lw9QNnG
    BACKEND_URL: AgAEHXeUyj9DYd1ll9/sHlArVyplkT3uvgA63L9AyYWQgZh3ejCBgtDNgJ2jAtjlNQvLxnMHK8ywdrI15ZzXF0UysnWiyxtiLBXeezTCW/oZDkKYaDFPEVijqWh1e7YTkPCHL8Aecquk9MqCTNxKflFinMpiB3M9SrTpA0HLzw03F29diDJPghvHPpncBWOndA5lGgk6si5/WUuo8dIqu+ohsunFxt41G2UVbLX9XARVf4w0dPGBLfA622dcp5tTVGizxcMroysGirlaCPVFHcHQuVdKTAAaQ7cINyrzZRwMi8yq/VeyjreObmPEfmNvKa+roS2Q66y4+JO6pkFzDi2zK/AyOKEWCRAvPTYSzVUJKxMjLKlQcaeMYhYBofGQ+bBBpbC7ORATAadmnFKv4urXOWKm7eaCzYMy3wihyR5tEaivuRyLcTedQ2RfbwqYdE0UypgQt6qts/0hxFCN7RFlsirr6ooXOLSUKSVTZ5pqby26bd+XknfbnGfpPQ3n485TfepZFZSYfzDXnNNHUR3+o4JtvZ3gnNKjTu6eRrSXi2Pi1VATPIK1mzEvG/fa+RI57qrZMK4tCS+DmWAG16mcNDMYa2yTMcJ6o431kbfW4LVVfUVgt6ic8aJeEYLOAtJZbIVVbyvaiQviNC+GZ8l5fbu7TU309sDL31jt7sLPHBY3bVVxQdsjKKdturPQU4Fm73wPj2bsF9GQanfjHys2mmO4
  template:
    metadata:
      creationTimestamp: null
      name: frontend-secrets
      namespace: dev-system
    type: Opaque
