---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-secrets
  namespace: dev-system
spec:
  encryptedData:
    B_DOMAIN: AgAHHxPI36GDYPpZSawGmGciDDNcIj1Gcqv4XVY+LCwv4zfXdcY6NvLiXShAbI1r+BzkkNosZfZZ6E4CsxUyqOj+T4iCMD+j3fVymPsKum+5dTAeypBq5jpm5yFIsOFEiQNA34m1MktuN5qSnrIaHVMPDQNtpOFULmk+spssrbCGi75anzYtbUVL1+VS8xHm+yQJnBY+aQnWRxd2ummumUg/9nnsY9UL+/AXfioX/5B9e/YZEXHpsZU1ays3NkPVhps5PpqmeKTTOe7qGo3ol2tZMwhFzmJ3LtuxHaDvcAW5Y1R3r27uY2Y//GBMQ68Asx9q1niqHtWROAY1zomhnTWGW7IPX0NUWMmrE8NQ+P9EXtO3cDKwSBjg2viekmU389SUFF+MPbUAP4SDvVqrKU6SPrZwFIAFSulbOWWoLncOSDNbZgSQDCBOkaQoX/XC88Uk16qollCykUFRsbFZjMpluvAiJ402vSo/PtqiPNKIW2bitrDswcuBMX854vN9A0sIaaokmR4ujd1O25Bfi/7CFFVn7CjSRl5Ob4yZKw3AQZ5033hWXA5+sbo6O5Sk46Nir8I9galq8TQC/IhJltU628lRPdzD1q64ghh64va+NN+owVx+VMrQVaSz/RzMEXLIh1NvkGwHrJnA+j7Owx10GRJNDZm/VrNJSqXL5piOz+D741cKtSISrwvfXQTtWitsx11TFa2zrwqRRm+5KV1+KDo=
    BACKEND_URL: AgBnVpgA7R/VvqKck9SE0P6vxM/i8Kjnms4QgW1vidUDanwJUuYTA5+3AKnRVFWx3zjSP+0zFG99MXscc55xeAk8C0vEZoR8R2jKlRy5Na6PZY/9DS0ikkJZfKa3dFxPK04Fj3EqAj2vmKqSjzDAOqv8MHRAezIw5NgA2AZCX8J/k3HDfyNxFhY1JlzmFxuGPueyp6MpGN5H02JqRBNkXoSIBSTuflQzsGtFfdF/4I51bax5wojfQu2D6y6or4uSLwSYyCnJy9VeRuSy47fSbIuO8IlcDJL/5hlptVpnlRct3oi8PsV6verahOdPWpzxxQSeRlN4SMvFBRE7aLkmrdgo/dF3VFwV27FTt0DMZUnxX1c1mwN2j4oho4dAV+SbHoOHlwW8O/7oerQIYdq07EgbUxfmZUvB6QirWk+SPqjSkVxvZ0RTG/3+u8E6XtoGT6Ole9ZicZkjFNevuGf6FBsaQUhi9Go+GrVD/JMPwCwE6SD2OC78SBA2tTXG/t4Z0zrDsaWsJo7TVmF6MIPxfCfnPgts9ekZs0QbRs3t+KXZQHXtkzsSwzU108fMnAlKbFE/B+W33fUz2K9dIW7/VZM71sY/4S3cCzFAzUPVqUPjvqc1MUUP8gSPpYP6BpauzRmAC0xGWmzUO5pKgIwtQzsINdynNruVMr+WxsV68QHCBxhy1g4kl+vVuD5ccBOaeCSdHMbSHiPglguvcMzxKPG0DQ+w
  template:
    metadata:
      creationTimestamp: null
      name: frontend-secrets
      namespace: dev-system
    type: Opaque
