---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-secrets
  namespace: dev-system
spec:
  encryptedData:
    B_DOMAIN: AgCTNXHAwx/S7DgqU2zUj0VsN8Us5fPVODN0+PRXf5XIx3k8FKcbF6NE7iUmNN1EeeEGXxctMwjv/bJbTMzUZuYTA5bLSGbWlcFzunyYPopvDp7EwcU0YJiomg4/0EsoqVba6mBrJS+pU2d/Znm3kfhMvJMgqfKhpXalIphcqR9xZoxwngQl0F/WsEhoX50fpsTFmIoqVwfGEmhQbbeQTz1+yGIXJOt/8iwq8QPlT6+uhRBCWMzj2jTmYANbEd1nX/sQmMNzVr79DGk/TlHDep5g9tK5Y5CH6FkvZ0xbTRE2gmUEY5cIm/0xC1ms38pz9u1pn0nkHKAYcNKUt5LEFsvFP0ekIqNCJGcS6fhLms2gd1n7qMJuHBzxoY5unU39WgwE2djjYw4s3Tumwsa3Ddo6okTP/HNLM4iDrv1W+VFFIvr3E3QGwkfpzTqkGoQjr524eQPIpWbKO9rbGRAXb8aF28iicMIULuTs+y2Z2FXALKeUZf6/ArUncDs2dbnC7ke9ay522POV64Uk+JlbhvLBbjvFzlz42Bz9skogn42Z4PUVwb2X7U4yP22R/lDZQ1YMgF4iuhVSkH0zMb0JfmhDZNbr8wchd7c6GKpwAPIPF1JNlJjAZNyP+5xjOsN+9rfxEwPCsZervpP+8dIHCkMBM9Sr2Y3wlkb2sNbu/hO0XeBjiwmCYNrs8QaFfNP/t7hnbCWvo6mP4QnIQ0whNhCyLPo=
    BACKEND_URL: AgAZPs108ZTmrB7NBdxLsKXZUVcnFU33kvc+TkRryrFPhx1V05aBflg939ShFN6jL2VXYua0plMqe2IsFFS/C3PNRJ7Qvqg0dXcIr/dv0EGPtmOkOlskPqnu7LZjZvYHagEs5Fz2RCee9L8R04eWAhCMVWtuOUnexM6Gqdw5CrWkB9L28jhb7SFFl6Uwgrvh+c3A6uW3aXuAJKe3WVI1ySHH2W0kKq9ZOGO4ixdk5O6GwksXduWyKzXFhCvrPPW6xLacPuUl054YxC0yKagisS0wxLxJZY1N91GEw4fGMKWZ31X/UZwHTCsMH50vkx8wWzmS9cd4OxF5ggtv/pDf5wGLGO8X7KOnuds6mmC1G6a4OnEM+pVfuJfHL6lJvH7L+zKgnyH2eouOyL0EUY+6SnHB9vn5cZ16O/iTL3S5mJdHkBCUfaOgX/XaT1ovC8yLNKyNrP8coIaLtGYshOQ1PjO4+4pO5jyKihdn+zGtMRC9hyk9ZkMPEyM7phZRvw0F0sXMvDIn+TEfZyckML5Bi+48kZWgMrD1eCrEh33XlrTla0ilabckHxSyKAr603mLbMUispOjAiIeYvZH6hQZXZMkQW74sbXjbTDlm43RLSR+Pb9SXlGwP6ejeMsyBYI8zD1o5sMd8256xluj7vvlghmtOxu8oSLPmnZb/X7dslwpeFnxN2CE4kHJQswugf/TknKWRIe0CU7G0hczBqGAtJx4Njg/
  template:
    metadata:
      creationTimestamp: null
      name: frontend-secrets
      namespace: dev-system
    type: Opaque
