---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-secrets
  namespace: dev-system
spec:
  encryptedData:
    B_DOMAIN: AgAo30nJsczrU1CAP3x996Nx6EYo08lqF0A8r9Qf2dwbV0AHqzyQTJC1FXKlqA46ufKJUdu5eUrgCcd5sZl1Wehh3qbRVfybO96BOY1jarQvjAq9nY93jmI0QPeClwjchEMbnq9DJXGPyqVtabsdkav0wDKhNIA65b9lEOsnWNqlZ0T53FqqlJ+tipw5td8Uzy6hWsn6ERQrC0GW3y3KybeD+8wJcXBDNbopYa4isBjdA9CNQZxFMip8N3OfbNCEqHCOiD+Z/XIMcJscuaT86TaLdHyR2aGXzWamH0GW2ct8zwDHnsGDeF60U3LiN+RS1KdvAa1tyQhapfY+mTZAWHQzqYS6fSWIOl/8qrTaMKDG8CxqPGx3Mmh1BtIL1MXCUim+Za4l1g6HPyuCmdUG7la7v95ex0qX2+H10ZqYQgKy164VIAGs+nzO7uixVgmiiozng6YueScVOSDK2H6iOTP6Udz2D+C4XklslMoF2D/L8miWQ4ACyXYuplsXT3YYfKk8kseO2STNs7t3ghpSO5WdVgQJEP22Z4idKu+TYXErqTPMh/Pb5lE4f3p9/AwvYV6scTKjbHcVWll72B1dyS7tp8b3kTkUzxHPuD5wYRsxqrZosPOQhrNgfGwJKP5k0zQkGFrFdmRawwAfx8OKMJ6xXgCHgfswL4mBU4nmUc0UGJh5/+9hqgpQe4yqxnd8fN1LL12HB6BQLZLVJL1d3xG7Mpc=
    BACKEND_URL: AgCToBqgCOHN/0n0xUM7Ko9Dl7GXCS+z5c3jvfd2r9Byf18tMM5Mg+s3m/uVb/7sRrAPFtsS++HqZFVCob8xoV1rIwGG6jHl9yckaZfBZj7L3l4+ZbuZCr8x2u3L1fXqCdTcFL3ENsI+4LQ2icLzQB7rMTO75PUvun2pwC3BtkNo/JbJASGxKxrQeAIcX8ZkShVCcH6FptLJ1UYWybYrdVce6Nxn3e+TyanCf4JZGEMXSqEpwKo0VXaukRtZqB30xZjSSZvLvYivxzQHGgyXDG+1QmEoMk+nbTNAn0C0H/Brap2OGK0vfqSpwFrG+w3meFzfUX+pTTOs0yty3h5zsSx02tVVFxFEySEbzPhJM9SKHz+Imz7WDVNupgW9dHrLdrucxO0TYYdBBt92+Vav3QdeZLzk7Ury3v27WKMuZNSmRynu82uQNx1GlMilPEcIa1p38e9GCPi26EQbmFP9GBCMNFZjBwMw3nR3twfhC5//26A+gFF8wZkeY+XulFSpMikV/ceHC3tTFpBjLT6pZipOZ94ScsQpKjwaFkOKQAb8HxZK64q9wRClZFM0aAvu++eIcZ+JAh2G8KUPCEW73i5fisTWu+ng+dRE8xmhpAK2ZotVAs0LE5vR3XvE5BMSigxstKd6dTXUrR1S3/nIb9s88jFn2cJNROe9x9M0GglxK2i8fd65Eh2yd3UzeutKY0PjzT9EVWGt1pEPJNDLTnTduzFV
  template:
    metadata:
      creationTimestamp: null
      name: frontend-secrets
      namespace: dev-system
    type: Opaque
