---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-secrets
  namespace: dev-system
spec:
  encryptedData:
    B_DOMAIN: AgCPvP9HkfhOEkUlLtL5uhX/sAJyFWjVGWSx2wmkdenLRPz47nVRXMm3DhJWS7JaD8HPWrJJYCQc7hGWIYpYKH4P8i6FN604e7gT/XptjflWLeb9bGYbWuB3cB72TkiQYyPIxnpp1FlKtewbbffDW2EiXDpIyDX0JxRGJEuHuIlhpqY2JOTgDw/16/rGuI+1UywLHrd3d9i6htgqFt49zVjPp//oEghMop+7/Yv5YuGKJweGBTPAFoCJtC+hNCNAJMs+ZcoWMkZeMWQZ69VXklBBGSUqCj73e6u6uRgxhgmfrrBQH1kxnQwEtf/wxXVIaZx6PEiVPRImaGIRIkr3oYA+7NHBiiW0puiwRHjUDIxVnOk2XZ4zP9Qpx4WHPFaWiNBPc51pucZT4TL6t/YzwemhOX4pXQaXqDfoPT3+GoJJVFWka6onwt+cM4P8E6wy58867IDSvUHzz8MzXDXUz3eOFQaBAh/AP9kE6LeSE9UcRs96v0DqTodU7Q0lMj57MDpyjhSkMxNi9JpAZe0rJsikjrAysQ4ZVRbqy4DZUgzDj8hlbmOkWQLtHui90I8sqHY8du22phPG27KNI8IPo6rg/UY4Gh2KoZaJ5iXmzwJwE4yecc84b3JwSAtkE1XSpG7lP4yWHKJlb4zZyw7joTzP5PJTM2owSItAfgh88wiVR9ohj1Vcg2WbSwEZ5BrCA5iKCDY7I9+YhQ2oatO7fpU5rYs=
    BACKEND_URL: AgCCmmcWqMoexW6lOoZuXJIR5iKYbTUnu970VveUTWR4N8p5itq8E9W90YfNcqGg9XdmOYIJ2SNMwQxQRP8Ct0beV4NZRRTbGLyHfdwpztwl2riu7/VU6b8iK5hzz7f1bUy3jiqbs7dYeuTTwoyQ3i7DztmGYxMkNzd9BBRZChVK0I82v5PjZApko5bqkuSnZqhLsH129oELHFgMPqfE/qipRHtW8zW+HVvzPw3eKzalD/qdcSEH4Sfb08zdFk7wHTEJQG7iB/p1ZCTBENwzDCYzOOt4wp7lmeGOrguu6V5ZYI7I68C2OCDPZVgMZ0w82vKPfHUDhea+CawkL+ViC3JgIIhcejz6khE+wzjqf1WYlDS49FTrk6LYAla+NAa8j0u5AM9CGy/Lfq1gq7yi8LRQqLmOZoVgsyT0IkUjXTNQ4LXWisQhj4eIBXV5NrPdMnNMQ9lQuOcVKN00K5qw6JPAxqMb8jhp17N2hltOiy81YLj14tyJnOsG+iJvx1UCuBqaqlu/3z91rUA/12Fp1GEBIYM8zh71NkbYqFCGxNZeTuA6OzQwUh11HuYZ6BLeIk/NsZykeOeag2ZyxOiyTvcNuWFnAWbqkNReAq9lh9ukcj4Enn5XfG709k6xJh5qxAVMjdCltuiP99VIylyyegRdXnYaMEE7yVxtNjYpjtCr0q4Ti89lEQqJ2CEKssncTl2i6xGia2oT50nQG0P9jU3LpBtj
  template:
    metadata:
      creationTimestamp: null
      name: frontend-secrets
      namespace: dev-system
    type: Opaque
