---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-secrets
  namespace: dev-system
spec:
  encryptedData:
    B_DOMAIN: AgBi9LXiJZNcXcXlbUVBcz6RZgKIdbuAlrJqS+J3emWKJNkZ7PHkQ48a+vjkrLlW9yyON9TV/9QwJ20pgigTTMyK4wX8FnfUIwK9Aqk/mp1i8l5AudKlivTS57rfzyzwECaLNcU3A0fqmWrRp/aBE2SNUWvfwB8XUTrEXDK0xniB2R1jk37GzXCGHhbMv3eRDXRA68LFPdr+2pjUAtUISpKCrYDHP0UZTMDeZZAIZzu4B2rS3Tm6Mdgb7vIJDy+2b8RFuqciUVHaaIkkfZWHJ0GsgljiJR+UfbHF6AhVzPzqZ+b68wDJ5vg4rO4JybXba7nTm5m/H6F3oE9DLwzZ1M8Na9M8Agx8ARPkOsNUPNpXyEPlpobBa3Yc+GgO6k2pEyRB3PE//Uph5r7shI05cu+VWYiZRi+TM5OA3Q+vrRSMdpl1jsLQjBcTlwTXPF23LugFPO90HEvHKcz5mJGU2wrY9rf5n13UGAjtrzUq2CU+92G/fMsjceM64Gtc4UFFpFJzfLYgh5vU+SiEB6WG3uPOH/2EWEFKULo1Xd19mOVHZ4RMk/Ae8ns94d3bWh3E18DMptVishHaqYRRcWs16vmkhJ3wQhb69aSeusDsZGx/AADYsgJK1EEoFrIiYDFeWnyWm8NVvmHgVHqcOGtkUfMPaQXdTfEPaimVe20DgHBgj+VFi17R63uYNdksSYNnipUnMyF25PoySSKqClPk/tdArp0/
    BACKEND_URL: AgCRoWLjdQ3qUtK5pzYxdVrTIv4mK1Tha+qmxA6TdT3dProSt8LoywIrNcZ5JKgjGmaOJ7fX8TVHIrXIIVzUXT9gxfWRhQyXtUpYlRgtvgWzXDgNUeONuwNpym/5SeV5Lr/3PCFCD3PoRjwLelWiz5LMkq9ybmIEgH1AnUCwKp+P4OrM2kY1PXovfXsmQYJHQpZuucmtOjpUU8ipiAwXwrIWIS7ei0yAZ9oLMBBSzIFLIybO5hJ3ueCrCrBIKZssuNPWewlVd1fyf/aFdDI7Tr8JaxfJT8i6beYefD1xwg1ebpBN56esJirPSnY/oR2A787Z0SRZZR+/NgjKwm5/SS7+uU7o47pHdXk5/pBuWHeOQJfV/LgppisylxxDOO9pRZ09myg0kbqaqzRyNoLZUPFLdAWxWB80vgO0xkWZ+AJviHEfsTzHOQDGeq9X9leSrfzwSBOZE4hddAvoWOZ/fQdqcQJo9eQTFF+KCXd4YqAyAr6yIr5Qh2rA4YuBoORkREZKVFWK48bpqiELFJqnM0PmVXZsVnZDfotHuMg0InVNtWqAGZDVMAGx0g53OqaEXW9wWUxBbTqyH5VXyDxjfaqaxF1LOqcoZxmYg5ugmejv0shabU1pGN9mqsneLFyG0oS7NaLo6C/n3xtLR7LRmy0eMq+myaUEDX79hgr5gjAr7jcmTl/hJz2CuB/+XToXFRjfafbEhY17ylFW2BVZa31qDVGB
  template:
    metadata:
      creationTimestamp: null
      name: frontend-secrets
      namespace: dev-system
    type: Opaque
