---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-secrets
  namespace: dev-system
spec:
  encryptedData:
    B_DOMAIN: AgAwm5Y96zQHMg3UP7KcFDgmjvd0bcWX80078IhJGgHNi00wRCtVMrxHI2Pk7FvC9duIomczEVFpXC6bep9vBDBipQyCA4jl8wVfvjn1c1DkAYITuxk0RwSu/Uva7jp1lNOwIcIp1o8sdKuJr94JcnEio0dk2zwg9ZVU5OqGeNoPN+3MuERzkcHpDSzBRb6G4zKkRNR7KUCXMVF709Z0Ng2ZGsGnkBnp1Jul4pPnemuXktL7yRcvZP0X1lsrcLKP+lJucwYxQshLwXCsAftocL6vvGO1ZuvOJ2tc8wTLZE+HZu1+Gr7ebdDlNuYDSIGEt7T6MNo6aL4q0ZbfN/nUSCHLVauZVxwhVW3jQpLR9I1E7GLVHt9NPoYmMM4ouu+qBT9VSxhUIxsma6sRWI8Z47MHL0mJRx2byuPbKYgR5s4754VJ/7l4vZhK7OYFDZhFq7VF6P6oht0UUuCtb3wAgzVQZk8bGUc7uFCtYqnWL9kxxeqpZPo6IM0/ttu5IIBVOLawo63xAGsl+OY/NdniNREhSQnfDBl3/YqX6JinkiCPb3oaTJkFgr0fj8NIdBb04dUAyxWdIxRJS/u6Ui8VnU5TdtYsc6dUeWYi7ZuOOGg0yXNG9ob1im12KppfyXbjQMdl2vi+cRbP8zbmYtdiQ1a+fZb1gLaHS+SSwdaVOHavi0x0g7/bowJ5+zn8GTnMjsgBh+5FlCmiTi/MwHAVI8BM9NM=
    BACKEND_URL: AgBBzRvWt4oacyNwgCm/841NJHO1zot2cYAFu0XDvH7AeWyukolwrRj6gPP5AsHcPZWv54EU10TRa3JTvxfWBzybBN6tb0U+CljKkFnZjkU4ig1pGzcrXXenGjnakkXtYByXFEw6QMpvHx13j0C2bMosNBRl5NflmP/Qk/dwl1JzQ1AZDJ5jqilrHNcBHrE9+6sMO+T/f0I/lRpa5N7xIEmozUm//SgwyjtcUMC+CF22mKzHc3x1a2FyQGvvKaVnC780y+oQpdPpbqHF3yLqRJMdpg90l8HaaZSGVVZLd6e/JCZ9xnRoqjLEtn1lhr5sUoqOstEm0NULt5K80yC+smusf7GIbWwrKpfLV1FdqrrcG2DmFiqVlOubNmdSOBXFlcJI4F9DT21jsMSPiA7wvIzHcB32wCFY6Q3k8ykmDppIxPzEQ2AEcBHdjxT1rLw7uOG30nXimfdnLhe/Kg2L0ib5y1fWTkK6YXyxWLAvodXpQUw4s5d8wI41VhQeoQ4ACAvIBstGdKvTVizOr8keGamkL8MeYxmH78MiG3a5+AzDg2PNJUVG2xfLARjgMkOI6wdIq8QpQ+swQmFuKQwtJwkfMD8fYwJmaBKnkbeGZEFCAfcu8stbgmYcE8VBWsNErtgdPVjpIC3UKSA8MRCBZBxPCJggBfuj9t2uMd50prXgn0VAStiBip3xEFqrlq0piXILkEkncEujuyGaItWKCeTD4jpu
  template:
    metadata:
      creationTimestamp: null
      name: frontend-secrets
      namespace: dev-system
    type: Opaque
