---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-secrets
  namespace: prod-system
spec:
  encryptedData:
    BACKEND_URL: AgAF+deoCkLFoCDBeC9XpseY5rhcUGHEY7A2LVts4hfpLo1IUz/ZBVbVXYfEIpXwJcNYIMOdG7N9bRth+sCkISIBp7V7RCL6e736k8d2qCpSeVu13dARAVfxOwMlybpg5ESY83R1gLF/AOHIvL39p5DBu9RgGb1zMeKUEe22TI4pmCIQliXp15QRIj393onsFPx/FKPeeEf0OANrL+HcYq9NfmLKjU2HQaXgHU8cdQ0Lo532AsYtgYBEHxGAZjPRA9Y8ymNEUXbhciQedoH0zmd98E4U/V/tC+djhm7EOHMOE3by7oyk0/xLPNxOtSt/acYBte1UCHYWBv9ETg1B4CX9j3WalAUiIhUgiJBXII+os2bd9L4UAOrQQlZQqOKgnCmAjAL0yBRviuQk4YcaAK012ASparH/cvgXzbZc7mY4UrJD98YhNIyOy0BhU7B45h8P5qrr71Qs7iNVyvM9th1h9qdST6z6tZLqBmbG+abgwbIrrqG13SBA4HzPLaJ8P+hNl51ZPHyZRsIIa4yExhibhhpkZjPEaMgeC4l7mQFCEifOM8lEcIyXVxYM1pakgg4eYMhmP4gRZSjwPVAdKa1TThTf6nvycEfBDm03pYzXpk++Hfc+UsUDAoqybYwKMPFp77ds5E94dchbc++ruvVnmnZY29yyZcMuYLYc/ub49bhBW1p9QzSm2kUu6fYnu6Osl2Jzeyba6LqvdcD1pDrPd37l
  template:
    metadata:
      creationTimestamp: null
      name: frontend-secrets
      namespace: prod-system
    type: Opaque
