---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-secrets
  namespace: dev-system
spec:
  encryptedData:
    BACKEND_URL: AgAPXBu066H3DDWgLnWTKfDETGfHLbRETwywBaqB8rrhAb8f/4HT2u75FoSZS+hDeLfnzf6OrnlGVMu1j0+DrLqn1wiypGXS2pkJTkhb0qSTPjGpAhf1fBTquYDgSrlG+IVKGws+OdN9uA9dH7KrwkPmaV3fDO8njL1ON2E60n1pzsNbWU0eM17dAiushO3kytwZZnWZ6KZMvyWZPWLvStEJkazh+HvynY0JR5B3XA2+hkrA6E1047ZCtdrf9kDTm1EWH2Y1V5i24M7YClnbx/r7DV4BATR0gK0/XwCrHMMTQBdpnB7IAzxJmGG1zGcIy4emZ8nkoCUJeyS0iVSyGQMiHKOYlDVRJ0fk54tCFIHb55C0hBB0ucq+4H+KrBUfmGR5qOfHeg5x/nWyGadVY7QCUyMiHGsRljSFYw25kKpgBxNeljOQXluyxpfGalumXl3J7ZfvkwxRFzlkDQQR/eFqX8YyTDmVJjGvXvfdWqFT2fISSlfpveisSeZb/y2UbR22XZ0Whw+WDgfdQU1VT9CyRzNJmidJfFCfQtgHFzgHrJj/ZoigU/nHmkJJ+SzLFDJGpg1UFeuanU6xzdvIJ/nXYovuKZA0aH2caWIJk0Ylc1dz47lG/3mrv+G1vFk7tMDvLfhetl74plfdDz7/StwGfOjeUa/M0QLQ578DcW1GghuGQ5/74akghbkQZLnNqrZIevtzQ0JidWU3ZiLHzA0AFKym
  template:
    metadata:
      creationTimestamp: null
      name: frontend-secrets
      namespace: dev-system
    type: Opaque
