---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-secrets
  namespace: dev-system
spec:
  encryptedData:
    B_DOMAIN: AgArDTbhR7gw1Bof6dQD/E56LTVFK7Okx/A/kEseRgErSSo3kh5refPFOWioMmSG0eFWsyQTJFz5L7YJ3nGyFa0pcwO46ggvfxZD1yaXxFyqqpcI0VN+tTSSmpFmNEuVm6Y+goNI7C4hitpVHiD5QkYVp3UUD5BvQMApcW+o+6+mX+NK/RVOp6OkPZ5uvtqLKS8h3PDLyXCkXWnAkFRuz9MVA7ttNqMf8NQ36pdP5Bt9b0Twh9iIu6Chyd3O6gkqUg9BQ6rICHrOLphbsX+iqc+y2E2KDZOhrCumufVjun5zX3/JFzAxmgAwD4sNHVt7+v0teWJvkE4V9UzEmqQOTGaFbp5QSUh5c4iTKLYBZZMSWpBM7akR8gz3Ob0gjYaWCKQx7OKGA+9hx9abqhooEtltDYQK+pJzNdqUeUXlKZk/MeshsMrN9YdVuWcuMrt9hEWix76aPtApeihI7kiQwXJFkS6LVIeXZfk9G5sHGjKEzeI8VnSvxMuIeiBkf4m1tMsb2q9JGVEH8lPQ0N2ZmUCHkb7rj9eGzMQWG6FEuwyAqxOBssJmw7EEe1Z3byHf215+zp4tzsbOJ4vZ6/KbPDFJ6/NK+Uo46g0jqr6BYRruaoXsDCwV3bLYyftNeNfCA1vV9jXCauoiZZ29i6HOye0k6FO1Ne/D1f5pcj/dBH4Hnf9VMdkYxvbQBk6UjOOumfTdcSgRqAJ7+1gsmxHclTiQrh0=
    BACKEND_URL: AgBJGWBcetE2GH1ltxemKoO0LUzROUmcErNmm6nxj0ZCIsJYfH7HHe8sccglr6roIYwpHuISKIbAnbh2j7652PEjnavIYEtB4dKaxHKvQdj6vrVHONRTWD6/E6l/aOnMUbQX86g3WfuXQX1gSIRGce7vHY1JKFnC8eC9Tb21yJHZg/Wif3EG7Tmu0G8Del8Mb0yFLiybQXTpXx84pNWhzFvMDUFpwc2g8bQUkI739hy2FAGTdTO2WiBkEJOOMXUK+iWFCOlO97gC1Avm6p6qPFRfSq184+QRKJSu/jhC53/zPdLZJ3ZqQP3IUCEucG6BvnW++sDw9w9ClPaFdOGpNXBWiP3LohfZE886UjRBTb8FCFRgNWH32FX2op7SrOmGgLxXoD+6QrJCot32EMQ91DD/bC+uPuoICJ8puNRXN+Z3aqL+/wJjy53FUjYZ9/B/cnLnXj3gj5J3854hNShPaCXV/uzkGGQPvO8Njd5PZG35HhKpE6APRbLIxleQBaMDqSp5szST48e9tFWcoGLPmbOFiiv3PhyPiVUzYFMf+f9BL1F38yBU3+QtUZrRHsgVRSkc4gIxKEX3lr8skHAeWiIS1AfLhDmmyNSWcLj+5Ah0c3epF4qTtj79ir9R3zLgDLoivX5oNG9WJFp7cpbC/Ijq8ZkxurGyZJOgoJimD9bVFkegm6VYkbnuoYQoyZdBNqXrLbKD45/GbV6YolIH6+KTv3Bz
  template:
    metadata:
      creationTimestamp: null
      name: frontend-secrets
      namespace: dev-system
    type: Opaque
